### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by svenssonjoel**
I added LispBM at the bottom of the MISC entries.

### CODE REVIEW

**Comment by dundalek** [comment]
Cool! I have some questions, depending on the answers maybe we could craft the description to be more informative.

- uLisp is probably the biggest name lisp for microcontrollers. How would you compare it, what are some of the differences and distinguishing features?
- In the readme you mention taking inspiration from both Scheme and CL. This seems unusual, implementations commonly tend to lean towards one or the other (or being different from both, e.g. Clojure-like). I am curious which major features are Scheme-like and which ones CL-like?
- The tagline claims concurrency inspired by Erlang. I wanted to learn more, but in the language reference the Concurrency and Semantics section has "TODO: Finish section." In what way is the concurrency similar?

**Comment by svenssonjoel** [comment]
Thank you, 

That sounds great. Do you mean we do that here in the pull request?

1. I know very little about uLisp. LBM for me was about figuring these things out for myself without peeking too much at what others do. My understanding is that uLisp is MUCH more CL faithful than LBM is. 
2. I think the readme says "lisp" and "scheme" not CL specifically. I am more thinking of lisp and scheme in general  terms. lisp - linked lists, car, cdr, cons, quotation, macros and so on.  Scheme - simplicity, no object system and so on. 
3. Erlang has a share nothing principle to concurrency, LBM does not. LBM threads share the heap. But the similarities are in the message passing system. All LBM threads have a mailbox and you can send a message to a thread if you know the thread-id. There is also a way to  spawn and link threads in LBM  this means that if the child thread dies a message is sent to the parent that can then restart or handle the error. 

Above this, I am trying to strike a balance between small runtime system and useful features. Some features a traditional lisper would implement as libraries on top of a lisp. Pattern matching is such an example. I find pattern matching quite useful and to make it efficient on a very resource constrained target, pattern matching is built into the runtime system. 

Finally LBM has a small but very active set of users. This mainly comes from it being integrated into the VESC open source motor controller system. 

Thanks, have a good day!

**Comment by dundalek** [comment]
Awesome, thank you and sorry for the delay. I made slight edits and created a Lisps for Microcontrollers section.

**Comment by svenssonjoel** [comment]
Thanks a lot

**Pull request merged**
